# Generated by Django 2.2 on 2019-05-12 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sardana',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('file', models.FileField(upload_to='')),
                ('first_compass_position', models.DecimalField(decimal_places=3, max_digits=6)),
                ('number_curts', models.IntegerField()),
                ('number_llargs', models.IntegerField()),
                ('beats_per_minute_curts', models.DecimalField(decimal_places=2, max_digits=5)),
                ('beats_per_minute_llargs', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
    ]
