# Generated by Django 2.2 on 2019-05-12 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sardanas', '0002_auto_20190512_2034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sardana',
            name='file',
            field=models.FileField(blank=True, upload_to=''),
        ),
    ]
