dist: xenial
language: python
python:
  - "3.5"
  - "3.6"
  - "3.7"
  - "nightly"

services:
  - docker

before_install:
  - docker-compose up -d db

install:
  - pip install -r requirements.txt

script:
  - python manage.py test --settings=SardAppren.settings.base

after_script:
  - docker-compose up -d api