dist: xenial
language: python
python:
  - "3.5"
  - "3.6"
  - "3.7"
  - "nightly"

env:
  global:
  - 'SFTP_USER=[user]'
  - 'SFTP_PASSWORD=[password]'
  - 'HOST=[host]'
  - 'PATH=[path]'
after_success:
- curl --ftp-create-dirs
       -T filename
       sftp://${SFTP_USER}:${SFTP_PASSWORD}@${HOST}/${PATH}

services:
  - docker

before_install:
  - docker-compose up -d db

install:
  - pip install -r requirements.txt

script:
  - python manage.py test --settings=SardAppren.settings.docker

after_script:
  - docker-compose up -d api