version: '3'

services:
  db:
    image: postgres:11.2-alpine
    ports:
      - "8010:5432"
    environment:
      POSTGRES_DB: sardappren
      POSTGRES_USER: sardappren
      POSTGRES_PASSWORD: sardappren

