version: '3'

services:
  api:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db

  db:
    image: postgres:11.2-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: sardappren
      POSTGRES_USER: sardappren
      POSTGRES_PASSWORD: sardappren

